### ISSUE TITLE
Fresh install on Linux fails to download Rojo

### ISSUE THREAD

**Issue by Airwarfare** [rojo-rbx/foreman#13]
I did a fresh install of foreman on Ubuntu and Debian (both WSL) and it seems like the TOML parser is adding a caret to the version string causing the Github release matching to fail, here's the trace https://pastebin.com/shFReDkt.

Works fine on Windows with the same `foreman.toml`.

I don't know if this is because I am running it in the WSL or if its for all Linux systems

**Steps to reproduce**

- New Linux system with cargo
- `cargo install --git https://github.com/rojo-rbx/foreman.git`
- `foreman list`
- uncomment rojo in `~/.foreman/foreman.toml`
- `foreman install`

**Comment by LPGhatguy** [comment]
Hello! Sorry, I hadn't had this repository marked as watching, so I didn't see your issue for a few days.

At the time you filed this issue, there was no Linux binary release of Rojo for 0.5.0. Regardless of what version you would've specified (besides `0.6.0-alpha.1`), Rojo would've failed to install for Linux. I do not believe this is a bug with the TOML parser or anything else -- the error message you got was accurate, but maybe a little under-detailed.

I've since released Rojo 0.5.4, which does have pre-built Rojo binaries. You should try again now that that release exists. Feel free to re-open this issue if that version fails to install!
