### ISSUE TITLE
failed to compile `foreman v1.0.3`, intermediate artifacts can be found at

### ISSUE THREAD

**Issue by lucasgmarzolla** [rojo-rbx/foreman#47]
I can't install foreman because cargo keeps giving this error
![image_2022-03-21_172956](https://user-images.githubusercontent.com/48849097/159358498-e14aeeea-1b33-4217-8954-4c2a3c199e7d.png)

**Comment by OverHash** [comment]
Support for compiling binaries is generally not given. The error message actually states the problem here in a very polite tone:
> please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

If you are just trying to install foreman, it is recommended you use the prebuilt binaries from [the release](https://github.com/Roblox/foreman/releases/tag/v1.0.3) (which would be [foreman-1.0.3-win64.zip](https://github.com/Roblox/foreman/releases/download/v1.0.3/foreman-1.0.3-win64.zip) in your case)

**Comment by oltrep** [comment]
Thank you @OverHash, it is in fact simpler to use a prebuilt binary 🙂

**Comment by lucasgmarzolla** [comment]
Thanks you so much!
